heat_template_version: 2015-10-15

description: |
  Test Cloud Files CDN

resources:

  container:
    type: OS::Swift::Container
    properties:
      name: { get_param: "OS::stack_name" }

  container_cdn:
    type: Rackspace::Cloud::CloudFilesCDN
    properties:
      container: { get_resource: container }
      ttl: 3600

outputs:

  show:
    value: { get_attr: [ container_cdn, show ] }
    description: Show all attributes of the CDN configuration for the container

  cdn_url:
    value: { get_resource: container_cdn }
    description: The URI for downloading container objects over HTTP.

  ssl_url:
    value: { get_attr: [ container_cdn, ssl_uri ] }
    description: The URI for downloading container objects over HTTPS, using SSL.

  streaming_url:
    value: { get_attr: [ container_cdn, streaming_uri ] }
    description: |
      The URI for video streaming container objects that uses HTTP Dynamic
      Streaming from Adobe.

  ios_url:
    value: { get_attr: [ container_cdn, ios_uri ] }
    description: |
      The URI for video streaming container objects that uses HTTP Live
      Streaming from Apple.
